baseURL = 'https://minzhezhu.github.io/blog-main/'
title = 'ZMZBlog'
theme = 'hugo-theme-reimu'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
[languages.en]
languageName = "English"
weight = 2

